### ISSUE TITLE
question

### ISSUE THREAD

**Issue by master7720** [XeonLyfe/Bartender-Src#1]
whats the difference between Bartender and xyz Bartender

**Comment by PeterPePem** [comment]
xyz bartender is bartender's resource pack, Bartender is the src

**Comment by XeonLyfe** [comment]
The XYZ Bartender is the clients jar aka the mod you put in the mods file.
The Bartender-release is the Source Code for the corresponding Jar files.

**Comment by master7720** [comment]
ah ok
